### ISSUE TITLE
Missing import path

### ISSUE THREAD

**Issue by BlackEdder** [atilaneves/unit-threaded#40]
I tried setting up a minimal project as in the example, but get the following error

```
$ dub test
Generating test runner configuration '__test__unittest__' for 'unittest' (library).
Source file '/home/edwin/Documents/code/delaunay/bin/ut.d' not found in any import path.
```

My dub.json is:

``` yml
{
    "name": "delaunay",
    "authors": [
        "Edwin van Leeuwen"
    ],
    "description": "Delaunay triangulation algorithm written in D.",
    "copyright": "Copyright © 2016, Edwin van Leeuwen",
    "license": "BSL-1.0",
    "configurations": [
        { "name": "delaunay" },
        {
            "name": "unittest",
            "preBuildCommands": ["dub run unit-threaded -c gen_ut_main -- -f bin/ut.d"],
            "targettype": "executable",
            "mainSourceFile": "bin/ut.d",
            "dependencies": {
                "unit-threaded": "~>0.6.0"
            }
        }
    ]
}
```

I tried adding bin to the importpaths, but get a linker error then.
